### ISSUE TITLE
安装新版本后必须断电重启添加设备

### ISSUE THREAD

**Issue by Spring0131** [pingbu/FbeeHome#21]
步骤：
1：主页launcher-应用-智能网关
2：选中“智能网关”图标，按语音遥控器菜单键，卸载
3：再次安装智能网关apk
4：安装成功后，把网关接收端插入盒子
5：操作智能网关的添加设备
结果：无法添加（添加数次多添加不上），必须把盒子断电开机功能才恢复正常
期望结果：卸载重新安装不影响初始化

**Comment by pingbu** [comment]
3229上没能重现，考虑守护进程so未正确加载的可能。

**Comment by pingbu** [comment]
魔盒也没有重现，暂时关闭，有进一步反馈再重新打开
