### ISSUE TITLE
场景开关无法测试

### ISSUE THREAD

**Issue by Spring0131** [pingbu/FbeeHome#30]
### 一：复现步骤
1：绑定场景“我回来了”（场景为有效场景）
2：回到设备主页，光标定位在”场景开关1    我回来了”按语音遥控器的菜单键，调出设置页面
3：选“测试”
结果：打不开场景开关的测试页面

-------------------------------------------------------------------------------------------
二：其他信息
优先级：高 

所属应用：智能网关

对应模块：设备

测试信息：测试人员-黄春玲；测试场地-讯飞互动；测试时间-20180705

主机端信息：中兴过渡板：XF-ZX6716V2-XFBC-V01001

遥控器端信息：超脑盒子版遥控器
remote：XFRB203_A000_1101R05_1681
dongle：XFDAA200_A_1102R02_929

智家设备品牌和型号：zigbee 情景开关

语点版本：7.1.0500114

远场版本：

问题版本：v3.1_146-IFyBox_v3

**Comment by pingbu** [comment]
在150版本修复

**Comment by Spring0131** [comment]
在版本158中验证问题已经得到修复。但是也引发新的问题。旧问题先关闭。
byclhuang
2018-07-09
