### ISSUE TITLE
设备名称修改后不能即刻显示

### ISSUE THREAD

**Issue by Spring0131** [pingbu/FbeeHome#31]
**### **一：复现步骤
以开关为例
1：成功添加开关
2：选中“开关”，按遥控器OK，打开设置页面
3：编辑，进入编辑设备名称，比如取名为“q开关”，点“确定”
结果：还是显示第一次的名称“开关”，需要再按一次遥控器的返回键，才能显示新命名的“q开关”
备注：这不是什么大问题，但是如果不能即刻显示修改后的内容，恐怕客户会小小的误会吧。请评估。谢谢
****

==================================================
二：其他信息
优先级：中

所属应用：智能网关

对应模块：设备-编辑

测试信息：测试人员-黄春玲；测试场地-讯飞互动；测试时间-20180705

主机端信息：中兴过渡板：XF-ZX6716V2-XFBC-V01001

遥控器端信息：超脑盒子版遥控器
remote：XFRB203_A000_1101R05_1681
dongle：XFDAA200_A_1102R02_929

智家设备品牌和型号：zigBEE 智能开关

语点版本：7.1.0500114

远场版本：

问题版本：v3.1_146-IFyBox_v3

**Comment by pingbu** [comment]
在149版本中修复
