### ISSUE TITLE
初始场景点测试无效

### ISSUE THREAD

**Issue by Spring0131** [pingbu/FbeeHome#33]
**一：复现步骤
1：添加场景开关，显示“场景开关1、场景开关2、场景开关3、场景开关4”
2：选中“场景开关1、”按遥控器的编辑页面，点“测试”
结果：没有任何反应
期望结果：可以提示“请先绑定场景”之类的提示**

================================================================
二：其他信息
优先级：中

所属应用：智能网关

对应模块：设备-编辑

测试信息：测试人员-黄春玲；测试场地-讯飞互动；测试时间-20180709

主机端信息：中兴过渡板：XF-ZX6716V2-XFBC-V01001

遥控器端信息：超脑盒子版遥控器
remote：XFRB203_A000_1101R05_1681
dongle：XFDAA200_A_1102R02_929

智家设备品牌和型号：zigBEE 智能开关

语点版本：7.1.0500114

远场版本：

问题版本：v3.1_158-IFyBox_v3

**Comment by pingbu** [comment]
有道理，后续版本加入提示。

**Comment by pingbu** [comment]
161版本加入了 提示。
