### ISSUE TITLE
设备名称和场景名称一样就打不开设备的测试页面

### ISSUE THREAD

**Issue by Spring0131** [pingbu/FbeeHome#34]
**一：复现步骤
1：添加场景开关，显示“场景开关1、场景开关2、场景开关3、场景开关4”
2：选中“场景开关1”按遥控器的编辑页面，点“编辑”
3：编辑“场景开关1”为“我回来了”
4：编辑一个场景，命名为“我回来了”
5：回到设备，选中“我回来了”这个设备，按遥控器的ok键打开编辑页面，选“测试”点OK键
结果：无反应，点不开设备名称和场景都叫“我回来了”的测试页面**

============================================================
其他信息
优先级：中

所属应用：智能网关

对应模块：设备-测试

测试信息：测试人员-黄春玲；测试场地-讯飞互动；测试时间-20180709

主机端信息：中兴过渡板：XF-ZX6716V2-XFBC-V01001

遥控器端信息：超脑盒子版遥控器
remote：XFRB203_A000_1101R05_1681
dongle：XFDAA200_A_1102R02_929

智家设备品牌和型号：zigBEE 智能开关

语点版本：7.1.0500114

远场版本：

问题版本：v3.1_158-IFyBox_v3

**Comment by pingbu** [comment]
未重现。看例子是场景开关，场景开关本来就没有测试页面。
